---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: teslamate
  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        defaultContainerOptionsStrategy: merge
        defaultContainerOptions:
          envFrom:
            - secretRef:
                name: teslamate-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: true
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
        containers:
          app:
            env:
              CHECK_ORIGIN: true
              MQTT_HOST: mosquitto.database.svc.cluster.local
              PORT: &port 80
              TZ: America/Los_Angeles
              VIRTUAL_HOST: &host "{{ .Release.Name }}.perryhuynh.com"
            image:
              repository: mirror.gcr.io/teslamate/teslamate
              tag: 3.1.0@sha256:b7b8b21869d789d043f62b404dd689f55c601ef7d02222e92c0f5d596d0b1044
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health_check
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 10m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10001
    persistence:
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.perryhuynh.com"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    service:
      app:
        ports:
          http:
            port: *port
