---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie@sha256:sha256:b0949a3f70641d5c56a05e18df8d69a16fba66af479d0ac6b74ede71f6d4e84f
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
  monitoring:
    enablePodMonitor: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &parameters
        barmanObjectName: r2
        serverName: postgres
  bootstrap:
    recovery:
      source: source
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *parameters