---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": postgres
  podMetricsEndpoints:
  - port: metrics
