---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-connect
spec:
  provider:
    onepassword:
      connectHost: http://1password-connect.external-secrets.svc.cluster.local
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1password-connect-vault
            namespace: external-secrets
            key: OP_CONNECT_TOKEN
