---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 1password-connect-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: 1password-connect-credentials
    template:
      data:
        1password-credentials.json: '{{ .OP_SESSION_JSON }}'
  dataFrom:
    - extract:
        key: 1password
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 1password-connect-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: 1password-connect-vault-secret
    template:
      data:
        OP_CONNECT_TOKEN: '{{ .OP_CONNECT_TOKEN }}'
  dataFrom:
    - extract:
        key: 1password