---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-traces
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-traces
  interval: 1h
  values:
    global:
      image:
        registry: mirror.gcr.io
    server:
      fullnameOverride: victoria-traces
      retentionPeriod: 30d
      persistentVolume:
        enabled: true
        storageClassName: ceph-block
        size: 20Gi
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
      route:
        enabled: true
        hostnames:
          - traces.perryhuynh.com
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
      serviceMonitor:
        enabled: true
