---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dufs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        DUFS_AUTH: admin:{{ .password }}@/:rw|flate:{{ .flate_password }}@/flate:rw|@/flate
  dataFrom:
    - extract:
        key: dufs
