---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-secret
    template:
      data:
        KONFLATE_APP_CLIENT_ID: "{{ .bot_client_id }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ .bot_private_key }}"
        KONFLATE_APP_INSTALLATION_ID: "{{ .bot_installation_id }}"
        KONFLATE_TOKEN: "{{ .github_general_token }}"
        KONFLATE_WEBHOOK_SECRET: "{{ .konflate_webhook_secret }}"
  dataFrom:
    - extract:
        key: github
      rewrite:
        - regexp:
            source: "(.*)"
            target: "github_$1"
    - extract:
        key: github-bot
      rewrite:
        - regexp:
            source: "(.*)"
            target: "bot_$1"
    - extract:
        key: konflate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "konflate_$1"
