---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-webhook-token-secret
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .konflate_webhook_secret }}"
        KONFLATE_APP_CLIENT_ID: "{{ index . \"github_client_id\" }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ index . \"github_private_key.pem\" }}"
        KONFLATE_APP_INSTALLATION_ID: "{{ index . \"github_installation_id\" }}"
  dataFrom:
    - extract:
        key: github-bot
      rewrite:
        - regexp:
            source: "(.*)"
            target: "github_$1"
    - extract:
        key: konflate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "konflate_$1"
