---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 1h
  values:
    config:
      repo: github://perryhuynh/homelab
      statusChecks: true
      prComments: true
    secret:
      existingSecret: konflate-secret
    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy-external
          namespace: networking
      hostnames:
        - "{{ .Release.Name }}.perryhuynh.com"
    monitoring:
      serviceMonitor:
        enabled: true
    podAnnotations:
      reloader.stakater.com/auto: "true"
    resources:
      requests:
        cpu: 5m
      limits:
        memory: 1Gi
