---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dashbrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        DASHBRR__OIDC_CLIENT_ID: "{{ .oauth_client_id }}"
        DASHBRR__OIDC_CLIENT_SECRET: "{{ .oauth_client_secret }}"
  dataFrom:
    - extract:
        key: dashbrr
