---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app decent-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: decent-exporter
  values:
    fullnameOverride: *app
    config:
      decentUrl: http://de1pro.internal:8080
      logLevel: info
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
    monitoring:
      serviceMonitor:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          folder: observability
          matchLabels:
            dashboards: grafana
