---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        GO2RTC_HOMEKIT_CLIENT_ID_0: "{{ .go2rtc_homekit_client_id_0 }}"
        GO2RTC_HOMEKIT_CLIENT_ID_1: "{{ .go2rtc_homekit_client_id_1 }}"
        GO2RTC_HOMEKIT_CLIENT_PUBLIC_0: "{{ .go2rtc_homekit_client_public_0 }}"
        GO2RTC_HOMEKIT_CLIENT_PUBLIC_1: "{{ .go2rtc_homekit_client_public_1 }}"
        RING_REFRESH_TOKEN: "{{ .ring_refresh_token }}"
        RING_DRIVEWAY_CAMERA_ID: "{{ .ring_driveway_camera_id }}"
        RING_DRIVEWAY_DEVICE_ID: "{{ .ring_driveway_device_id }}"
        RING_FRONT_DOOR_CAMERA_ID: "{{ .ring_front_door_camera_id }}"
        RING_FRONT_DOOR_DEVICE_ID: "{{ .ring_front_door_device_id }}"
  dataFrom:
    - extract:
        key: go2rtc
      rewrite:
        - regexp:
            source: "(.*)"
            target: "go2rtc_$1"
    - extract:
        key: ring
      rewrite:
        - regexp:
            source: "(.*)"
            target: "ring_$1"
