---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: grafana-mcp
spec:
  instanceName: grafana
  name: grafana-mcp
  role: Viewer
  tokens:
    - name: grafana-mcp
      secretName: grafana-mcp-token
