---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: snmp-exporter-ups-rules
spec:
  groups:
    - name: snmp-exporter-ups.recording-rules
      rules:
        - record: upsAdvBatteryRunTimeRemaining
          expr: upsAdvBatteryRunTimeRemaining_seconds * 100
        - record: upsBasicBatteryTimeOnBattery
          expr: upsBasicBatteryTimeOnBattery_seconds * 100
    - name: snmp-exporter-ups.rules
      rules:
        - alert: UPSOnBattery
          expr: upsBasicBatteryTimeOnBattery_seconds > 60
          annotations:
            summary: >-
              ZPM {{$labels.instance}} is running on batteries
          for: 5m
          labels:
            severity: critical
        - alert: UPSReplaceBattery
          expr: upsAdvBattery_needsreplacing > 0
          annotations:
            summary: >-
              ZPM {{ $labels.instance }} battery needs to be replaced
          for: 5m
          labels:
            severity: critical
