---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .client_id }}"
        github_app_private_key: "{{ .private_key }}"
        github_app_installation_id: "{{ .installation_id }}"
  dataFrom:
    - extract:
        key: github-actions-runner
