---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homelab-actions-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  values:
    runnerScaleSetName: *app
    githubConfigUrl: https://github.com/perryhuynh/homelab
    githubConfigSecret: actions-runner-secret
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: ceph-block
        resources:
          requests:
            storage: 5Gi
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.336.0@sha256:281a9a090522fafbf4967f158b8c97d03552b1978b688893c5f7cb1944bc5fe5
            command:
              - "/home/runner/run.sh"
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            volumeMounts:
              - mountPath: /var/run/secrets/talos.dev
                name: talos
                readOnly: true
        serviceAccountName: *app
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
        volumes:
          - name: talos
            secret:
              secretName: *app
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app impling-tracker-actions-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  values:
    runnerScaleSetName: *app
    githubConfigUrl: https://github.com/perryhuynh/impling-tracker
    githubConfigSecret: actions-runner-secret
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.336.0@sha256:281a9a090522fafbf4967f158b8c97d03552b1978b688893c5f7cb1944bc5fe5
            command:
              - "/home/runner/run.sh"
