---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grafana-mcp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    extraArgs:
      - --disable-write
    grafana:
      apiKeySecret:
        name: grafana-mcp-token
        key: token
      url: http://grafana-service.observability.svc.cluster.local:3000
    image:
      registry: mirror.gcr.io
      tag: v0.15.2
    podAnnotations:
      reloader.stakater.com/auto: "true"
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
    route:
      main:
        enabled: true
        hostnames:
          - grafana-mcp.perryhuynh.com
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
