---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: echo-server
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: echo-server
      app.kubernetes.io/name: echo-server
  egress: []
