---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: scrypted
  values:
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              SCRYPTED_INSECURE_PORT: &port 80
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.144.1-noble-lite@sha256:97c6f8162f3cd59240fa742da5ee39bc0f4978c49fa8f1ad35e259fa8103a171
            command:
              - "npm"
            args:
              - "--prefix"
              - "/server"
              - "exec"
              - "scrypted-serve"
            resources:
              limits:
                memory: 8Gi
              requests:
                cpu: 100m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iot",
            "namespace": "networking",
            "ips": ["192.168.50.4/24"],
            "mac": "a6:42:05:ea:fc:5b"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: scrypted
        globalMounts:
          - path: /server/volume
      plugins:
        existingClaim: scrypted-plugins
        globalMounts:
          - path: /server/volume/plugins
      recs:
        type: nfs
        path: /mnt/tank/media
        server: nas.home.arpa
        globalMounts:
          - path: /recs
            subPath: scrypted
      tmpfs:
        type: emptyDir
        advancedMounts:
          scrypted:
            app:
              - path: /.cache
                subPath: cache
              - path: /home/ubuntu/.npm
                subPath: npm
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.perryhuynh.com"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        ports:
          http:
            port: *port
