---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubernetes-mcp-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    image:
      registry: quay.io
      repository: containers/kubernetes_mcp_server
      # renovate: datasource=docker depName=quay.io/containers/kubernetes_mcp_server
      version: v0.0.65@sha256:5df586e2c7ced2a3125f6e78923388d80b69de0a2ad1470325b05318f12725bd
    extraArgs:
      - --read-only
    ingress:
      enabled: false
    rbac:
      extraClusterRoleBindings:
        - name: view
          roleRef:
            name: view
            external: true
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
