---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: changedetection
spec:
  refreshPolicy: CreatedOnce
  target:
    template:
      data:
        TOKEN: "{{ .TOKEN }}"
        PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000/?token={{ .TOKEN }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "TOKEN"