---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: changedetection
  values:
    controllers:
      changedetection:
        annotations:
          reloader.stakater.com/auto: "true"
        defaultContainerOptionsStrategy: merge
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.55.7@sha256:736331d2787f94d3201b64aa641e090f67e28577ba505bd7ba5d7c1841e1e0ca
            env:
              BASE_URL: "https://changedetection.perryhuynh.com"
              DISABLE_VERSION_CHECK: "true"
              PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000/"
              PORT: &port 5000
              USE_X_SETTINGS: 1
              TZ: America/Los_Angeles
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /worker-health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 10m
            securityContext:
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
          browser:
            image:
              repository: ghcr.io/browserless/chromium
              tag: v2.54.1@sha256:5a0b8ffa43426549e9df7c822c68505e70f3817192ed111f81bd587a2a9e7229
            env:
              CONCURRENT: "10"
              DATA_DIR: /profile
              DOWNLOAD_DIR: /downloads
              TIMEOUT: "60000"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /active
                    port: 3000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 10m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          changedetection:
            app:
              - path: /datastore
                subPath: changedetection
      cache:
        existingClaim: changedetection-cache
        advancedMounts:
          changedetection:
            browser:
              - path: /downloads
                subPath: downloads
              - path: /profile
                subPath: profile
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.perryhuynh.com"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    service:
      app:
        ports:
          http:
            port: *port
