---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: "{APP}-dragonfly"
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.38.1@sha256:baf70ba7ad182a992b988497cfa31a488978c8fab7712079784c2401f447e402
  replicas: 2 #
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
  resources:
    requests:
      cpu: 10m
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      nodeTaintsPolicy: Honor
      labelSelector:
        matchLabels:
          app: "${APP}-dragonfly"
