---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lostcity
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: lostcity
  values:
    controllers:
      lostcity:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/perryhuynh/lostcity
              tag: 274@sha256:e5d416cf24c9f6246974da8227fba6ae910e19392aee2a379f5ee25fc6fd9867
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /crc
                    port: &port 8888
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              limits:
                memory: 4Gi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: lostcity
      cache:
        existingClaim: lostcity-cache
        globalMounts:
          - path: /app/content/pack
            subPath: content
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /app/engine/data/pack
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.perryhuynh.com"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    service:
      app:
        ports:
          http:
            port: *port
          management:
            port: 8898
    serviceMonitor:
      app:
        endpoints:
          - port: management
            path: prometheus
            
