---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-ebpf-instrumentation
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: opentelemetry-ebpf-instrumentation
  values:
    config:
      data:
        discovery:
          instrument:
            - k8s_deployment_name: "plex"
          trace_printer: text
          routes:
            unmatched: heuristic
          ebpf:
            context_propagation: all
            traffic_control_backend: tcx
            disable_blackbox_cp: true
            track_request_headers: true
        otel_traces_export:
          endpoint: http://otel-collector-headless.observability.svc.cluster.local:4317
    k8sCache:
      replicas: 1