---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/opentelemetry.io/instrumentation_v1alpha1.json
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default
spec:
  exporter:
    endpoint: http://gateway-collector-headless.observability.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  resource:
    addK8sUIDAttributes: true
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
    - name: OTEL_METRICS_EXPORTER
      value: "none"
  dotnet:
    env:
      - name: DOTNET_EnableDiagnostics
        value: "1"
      - name: DOTNET_EnableDiagnostics_Profiler
        value: "1"
  java:
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "true"
  python:
    env:
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: "true"
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "true"
