log:
  streams: debug # Prevent log spam from UniFi Protect
api:
  listen: :80
  origin: "*"
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 192.168.20.207:8555
    - stun:8555
  ice_servers:
    - urls:
        - stun:stun.cloudflare.com:3478
streams:
  driveway:
    - "ring:?camera_id=${RING_DRIVEWAY_CAMERA_ID}&device_id=${RING_DRIVEWAY_DEVICE_ID}&refresh_token=${RING_REFRESH_TOKEN}"
    - "ring:?camera_id=${RING_DRIVEWAY_CAMERA_ID}&device_id=${RING_DRIVEWAY_DEVICE_ID}&refresh_token=${RING_REFRESH_TOKEN}"
  front_door:
    - "ring:?camera_id=${RING_FRONT_DOOR_CAMERA_ID}&device_id=${RING_FRONT_DOOR_DEVICE_ID}&refresh_token=${RING_REFRESH_TOKEN}"
    - "ring:?camera_id=${RING_FRONT_DOOR_CAMERA_ID}&device_id=${RING_FRONT_DOOR_DEVICE_ID}&refresh_token=${RING_REFRESH_TOKEN}"
homekit:
  driveway:
    name: driveway
    pairings: &pairings
      - client_id=${GO2RTC_HOMEKIT_CLIENT_ID_0}&client_public=${GO2RTC_HOMEKIT_CLIENT_PUBLIC_0}&permissions=0
      - client_id=${GO2RTC_HOMEKIT_CLIENT_ID_1}&client_public=${GO2RTC_HOMEKIT_CLIENT_PUBLIC_1}&permissions=1
  front_door:
    name: front door
    pairings: *pairings
