---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/anubis
    - ../../../../components/dragonfly
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: dragonfly
      namespace: database
    - name: glauth
      namespace: security
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'Ready'
      current: status.phase == 'Ready'
  interval: 1h
  path: ./kubernetes/apps/security/authelia/app
  postBuild:
    substitute:
      APP: *app
      ANUBIS_TARGET: http://authelia.security.svc.cluster.local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
